server:
  port: 8761
spring:
  application:
    name: discovery-service
  profiles:
    active: development
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: false
    fetch-registry: false